/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AnalyticsUpdateManyWithoutUsersInput } from "./AnalyticsUpdateManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { BankAccountUpdateManyWithoutUsersInput } from "./BankAccountUpdateManyWithoutUsersInput";
import { ExpenseUpdateManyWithoutUsersInput } from "./ExpenseUpdateManyWithoutUsersInput";
import { MoneyUpdateManyWithoutUsersInput } from "./MoneyUpdateManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AnalyticsUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AnalyticsUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AnalyticsUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  analyticsItems?: AnalyticsUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => BankAccountUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => BankAccountUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => BankAccountUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  bankAccounts?: BankAccountUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => ExpenseUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ExpenseUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ExpenseUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  expenses?: ExpenseUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => MoneyUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MoneyUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MoneyUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  monies?: MoneyUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
